# Generated by Django 5.0.3 on 2024-04-12 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0004_news_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="view_count",
        ),
    ]
